name: jolideco-paper

channels:
    - defaults
    - conda-forge

variables:
    PYTHONNOUSERSITE: "1"

dependencies:
    - numpy
    - pip
    - python=3.10
    - astropy
    - scikit-image
    - scipy
    - gammapy=1.0
    -  pip:
        - showyourwork
        - matplotlib
        - git+https://adonath:${JOLIDECO_ACCESS_TOKEN}@github.com/adonath/jolideco.git
