name: jolideco-paper

channels:
    - defaults
    - conda-forge

variables:
    PYTHONNOUSERSITE: "1"

dependencies:
    - numpy
    - pip
    - python=3.10
    - astropy
    - scikit-image
    - scipy
    -   pip:
            - showyourwork
            - matplotlib
